// <auto-generated />
using System;
using Microled.Nfe.Service.Infra.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Microled.Nfe.Service.Infra.Migrations
{
    [DbContext(typeof(NfeDbContext))]
    [Migration("20261006190000_AddErrosEnvioToNotasFiscais")]
    partial class AddErrosEnvioToNotasFiscais
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microled.Nfe.Service.Domain.Entities.NotaFiscal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("alterado_por");

                    b.Property<string>("CnpjPrestador")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cnpj_prestador");

                    b.Property<string>("CodigoVerificacao")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_verificacao");

                    b.Property<string>("CpfCnpjTomador")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cpf_cnpj_tomador");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("criado_por");

                    b.Property<DateTimeOffset?>("DataCancelamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cancelamento");

                    b.Property<DateTimeOffset?>("DataEmissao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_emissao");

                    b.Property<DateTimeOffset?>("DataPagamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_pagamento");

                    b.Property<bool>("Pago")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("pago");

                    b.Property<decimal?>("ValorDepositado")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_depositado");

                    b.Property<string>("ErrosEnvio")
                        .HasColumnType("text")
                        .HasColumnName("erros_envio");

                    b.Property<string>("InscricaoPrestador")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("inscricao_prestador");

                    b.Property<string>("NumeroLote")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_lote");

                    b.Property<string>("NumeroNota")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_nota");

                    b.Property<string>("NumeroRps")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_rps");

                    b.Property<byte[]>("Pdf")
                        .HasColumnType("bytea")
                        .HasColumnName("pdf");

                    b.Property<string>("Protocolo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("protocolo");

                    b.Property<string>("SerieRps")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("serie_rps");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Xml")
                        .HasColumnType("text")
                        .HasColumnName("xml");

                    b.HasKey("Id");

                    b.HasIndex("CnpjPrestador");

                    b.HasIndex("CpfCnpjTomador");

                    b.HasIndex("CriadoEm");

                    b.HasIndex("DataEmissao");

                    b.HasIndex("NumeroNota");

                    b.HasIndex("Protocolo");

                    b.HasIndex("Status");

                    b.HasIndex("InscricaoPrestador", "SerieRps", "NumeroRps");

                    b.ToTable("notas_fiscais", (string)null);
                });

            modelBuilder.Entity("Microled.Nfe.Service.Domain.Entities.Tomador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("Bairro")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("cep");

                    b.Property<string>("CodigoMunicipio")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo_municipio");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("complemento");

                    b.Property<string>("CpfCnpj")
                        .HasMaxLength(14)
                        .IsRequired()
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cpf_cnpj");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("InscricaoEstadual")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("inscricao_estadual");

                    b.Property<string>("InscricaoMunicipal")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("inscricao_municipal");

                    b.Property<string>("Logradouro")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("logradouro");

                    b.Property<string>("Numero")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero");

                    b.Property<string>("RazaoSocial")
                        .HasMaxLength(200)
                        .IsRequired()
                        .HasColumnType("character varying(200)")
                        .HasColumnName("razao_social");

                    b.Property<string>("TipoLogradouro")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_logradouro");

                    b.Property<string>("Uf")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("uf");

                    b.HasKey("Id");

                    b.HasIndex("CpfCnpj")
                        .IsUnique();

                    b.HasIndex("RazaoSocial");

                    b.ToTable("tomadores", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
